export const ADD_LEAGUE = 'ADD_LEAGUE';
export const ADD_LEAGUE_SUCCESS = 'ADD_LEAGUE_SUCCESS';
export const ADD_LEAGUE_FAILURE = 'ADD_LEAGUE_FAILURE';
export const FETCH_LEAGUES = 'FETCH_LEAGUES';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';
export const FETCH_LEAGUES_FAILURE = 'FETCH_LEAGUES_FAILURE';
